typography_spectrum: 0.9316
color:
  brandColors:
    - '#cbcbcb'
    - '#a6adb2'
    - '#213758'
    - '#7193a6'
    - '#3e5e82'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.23603
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Christina Hannon
  email: hannon.christina@gmail.com
name: Christina Hannon
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Speaker and Coach
description: Speaker and Coach
purpose: []
