name: Christina Hannon
favicon: null
layout_spectrum: 0.16400093492120504
typography_spectrum: 0.6840715727303177
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#89912d'
    - '#f1a477'
    - '#864e28'
  brandStrength: 0.7690222016535699
  lightness: 0.4826911659911275
  saturation: 0.9549511286895722
  rhythmicContrast: 0.715342041105032
purpose: []
